"""
VibeCheck Analyzer — Core detection engine.
Analyzes a website's HTML, headers, and structure to determine
if it was likely built using AI-assisted "vibe coding" tools.
"""

import re
import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse


class Finding:
    """Represents a single detection finding."""

    def __init__(self, signal: str, description: str, confidence: str = "medium", evidence: str = ""):
        self.signal = signal
        self.description = description
        self.confidence = confidence  # "high", "medium", "low"
        self.evidence = evidence

    def to_dict(self):
        return {
            "signal": self.signal,
            "description": self.description,
            "confidence": self.confidence,
            "evidence": self.evidence,
        }


class CategoryResult:
    """Result for a single analysis category."""

    def __init__(self, name: str, icon: str, score: int = 0, findings: list = None):
        self.name = name
        self.icon = icon
        self.score = score
        self.findings = findings or []

    def to_dict(self):
        return {
            "name": self.name,
            "icon": self.icon,
            "score": self.score,
            "findings": [f.to_dict() for f in self.findings],
        }


class VibeCodingAnalyzer:
    """Main analyzer — fetches a URL and runs all heuristic checks."""

    # Category weights for overall score
    WEIGHTS = {
        "ai_platforms": 0.30,
        "ui_libraries": 0.15,
        "frameworks": 0.10,
        "content": 0.15,
        "code_style": 0.10,
        "deployment": 0.10,
        "design_patterns": 0.10,
    }

    # ── Generic marketing phrases commonly generated by AI ──────────────
    GENERIC_PHRASES = [
        r"transform your",
        r"revolutionize",
        r"empower your",
        r"take your .+ to the next level",
        r"unlock the (full )?power",
        r"supercharge your",
        r"streamline your",
        r"elevate your",
        r"reimagine",
        r"cutting[- ]edge",
        r"next[- ]gen(eration)?",
        r"state[- ]of[- ]the[- ]art",
        r"game[- ]chang(er|ing)",
        r"seamless(ly)?",
        r"effortless(ly)?",
        r"blazing[- ]fast",
        r"lightning[- ]fast",
        r"world[- ]class",
        r"enterprise[- ]grade",
        r"built for the future",
        r"designed for .+ by .+",
    ]

    GENERIC_CTAS = [
        "get started",
        "learn more",
        "sign up",
        "join now",
        "try it free",
        "start free trial",
        "book a demo",
        "request access",
        "join the waitlist",
        "coming soon",
        "start building",
        "get early access",
        "try for free",
    ]

    # ── shadcn/ui signature class combinations ──────────────────────────
    SHADCN_CLASS_PATTERNS = [
        "inline-flex items-center justify-center",
        "inline-flex items-center rounded-full border",
        "relative w-full rounded-lg border",
        "fixed inset-0 z-50 bg-black/80",
        "flex h-full w-full items-center justify-center rounded-full",
        "relative flex cursor-default select-none items-center rounded-sm",
        "shrink-0 rounded-sm border border-primary",
    ]

    # ── Cookie-cutter layout section order ──────────────────────────────
    TEMPLATE_SECTION_NAMES = [
        "hero",
        "features",
        "testimonials",
        "pricing",
        "faq",
        "cta",
        "footer",
    ]

    def analyze(self, url: str) -> dict:
        """Main entry — fetch + analyze a URL and return results."""
        # Normalise the URL
        if not url.startswith(("http://", "https://")):
            url = "https://" + url

        parsed = urlparse(url)

        # ── Fetch the page ──────────────────────────────────────────────
        try:
            headers_req = {
                "User-Agent": (
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/131.0.0.0 Safari/537.36"
                )
            }
            response = requests.get(url, headers=headers_req, timeout=15, allow_redirects=True)
            response.raise_for_status()
        except requests.RequestException as exc:
            return {"error": f"Failed to fetch {url}: {str(exc)}"}

        html = response.text
        resp_headers = dict(response.headers)
        soup = BeautifulSoup(html, "lxml")

        # ── Run every category ──────────────────────────────────────────
        categories = {
            "ai_platforms": self._check_ai_platforms(soup, html, resp_headers, parsed),
            "ui_libraries": self._check_ui_libraries(soup, html),
            "frameworks": self._check_frameworks(soup, html, resp_headers),
            "content": self._check_content(soup, html),
            "code_style": self._check_code_style(soup, html),
            "deployment": self._check_deployment(resp_headers, parsed, url),
            "design_patterns": self._check_design_patterns(soup, html),
        }

        # ── Compute overall weighted score ──────────────────────────────
        overall = sum(
            categories[cat].score * self.WEIGHTS[cat] for cat in categories
        )
        overall = min(100, int(round(overall)))

        verdict, verdict_emoji = self._get_verdict(overall)

        return {
            "url": url,
            "overall_score": overall,
            "verdict": verdict,
            "verdict_emoji": verdict_emoji,
            "categories": {k: v.to_dict() for k, v in categories.items()},
        }

    # ====================================================================
    # Category checkers
    # ====================================================================

    def _check_ai_platforms(self, soup, html, headers, parsed) -> CategoryResult:
        result = CategoryResult("AI Platform Signatures", "🤖")
        findings = []

        # ── v0.dev ──────────────────────────────────────────────────────
        if soup.find_all(attrs=lambda attrs: attrs and any(k.startswith("data-v0") for k in attrs)):
            findings.append(Finding("v0.dev", "Found data-v0-* attributes — strong v0.dev marker", "high", "data-v0-* attributes"))
        if "v0.dev" in html.lower():
            findings.append(Finding("v0.dev", "Reference to v0.dev found in page source", "high"))

        # ── Bolt.new / StackBlitz ───────────────────────────────────────
        for marker in ["bolt.new", "stackblitz"]:
            if marker in html.lower():
                findings.append(Finding("Bolt.new", f"Reference to {marker} found in source", "high"))
        if soup.find_all(attrs={"data-bolt": True}):
            findings.append(Finding("Bolt.new", "data-bolt attributes detected", "high"))

        # ── Lovable / GPTEngineer ───────────────────────────────────────
        for marker in ["lovable", "gptengineer", "gpt-engineer"]:
            if marker in html.lower():
                findings.append(Finding("Lovable", f"Reference to '{marker}' in source", "high"))

        meta_gen = soup.find("meta", attrs={"name": "generator"})
        if meta_gen:
            gen_content = (meta_gen.get("content") or "").lower()
            for name in ["v0", "bolt", "lovable", "gptengineer", "cursor", "windsurf", "replit"]:
                if name in gen_content:
                    findings.append(Finding(name, f"Meta generator tag contains '{name}'", "high", gen_content))

        # ── Vercel AI SDK ───────────────────────────────────────────────
        if re.search(r"@vercel/ai|ai/react|useChat|useCompletion", html):
            findings.append(Finding("Vercel AI SDK", "Vercel AI SDK references detected", "medium"))

        # ── Replit ──────────────────────────────────────────────────────
        if ".repl.co" in parsed.netloc or ".replit.dev" in parsed.netloc:
            findings.append(Finding("Replit", "Hosted on Replit domain", "medium"))
        if "replit" in html.lower():
            findings.append(Finding("Replit", "Reference to Replit in source", "medium"))

        # Score
        if findings:
            high_count = sum(1 for f in findings if f.confidence == "high")
            result.score = min(100, 40 + high_count * 20 + (len(findings) - high_count) * 10)
        result.findings = findings
        return result

    def _check_ui_libraries(self, soup, html) -> CategoryResult:
        result = CategoryResult("UI Library Patterns", "🧩")
        findings = []

        # ── Radix UI ────────────────────────────────────────────────────
        radix_attrs = soup.find_all(attrs=lambda a: a and any(k.startswith("data-radix") for k in a))
        if radix_attrs:
            count = len(radix_attrs)
            findings.append(Finding("Radix UI", f"Found {count} elements with data-radix-* attributes", "high", f"{count} elements"))

        if re.search(r"@radix-ui", html):
            findings.append(Finding("Radix UI", "Radix UI package reference in source", "high"))

        # ── shadcn/ui class patterns ────────────────────────────────────
        shadcn_matches = 0
        for pattern in self.SHADCN_CLASS_PATTERNS:
            if pattern in html:
                shadcn_matches += 1
        if shadcn_matches >= 2:
            findings.append(Finding("shadcn/ui", f"Detected {shadcn_matches} shadcn/ui class patterns", "high", f"{shadcn_matches} patterns matched"))
        elif shadcn_matches == 1:
            findings.append(Finding("shadcn/ui", "Possible shadcn/ui class pattern detected", "medium"))

        # ── CSS custom properties typical of shadcn ─────────────────────
        style_tags = soup.find_all("style")
        style_text = " ".join(s.string or "" for s in style_tags)
        shadcn_vars = ["--radius", "--primary", "--ring", "--card", "--popover", "--muted", "--accent", "--destructive"]
        var_hits = sum(1 for v in shadcn_vars if v in style_text or v in html)
        if var_hits >= 4:
            findings.append(Finding("shadcn/ui", f"Found {var_hits} shadcn-style CSS custom properties", "high", f"{var_hits}/8 variables"))
        elif var_hits >= 2:
            findings.append(Finding("shadcn/ui", f"Found {var_hits} possible shadcn CSS custom properties", "medium"))

        # ── Lucide Icons ────────────────────────────────────────────────
        lucide = soup.find_all(class_=re.compile(r"lucide"))
        if lucide:
            findings.append(Finding("Lucide Icons", f"Found {len(lucide)} Lucide icon elements", "medium"))
        if "lucide-react" in html or "lucide.dev" in html:
            findings.append(Finding("Lucide Icons", "Lucide icon library referenced", "medium"))

        # ── Heroicons ───────────────────────────────────────────────────
        if "heroicons" in html.lower():
            findings.append(Finding("Heroicons", "Heroicons library referenced", "low"))

        if findings:
            high_count = sum(1 for f in findings if f.confidence == "high")
            result.score = min(100, 20 + high_count * 20 + (len(findings) - high_count) * 8)
        result.findings = findings
        return result

    def _check_frameworks(self, soup, html, headers) -> CategoryResult:
        result = CategoryResult("Framework Detection", "⚡")
        findings = []

        # ── Next.js ─────────────────────────────────────────────────────
        next_div = soup.find(id="__next")
        if next_div:
            findings.append(Finding("Next.js", "Found #__next root element", "high"))
        if "/_next/static" in html or "/_next/data" in html:
            findings.append(Finding("Next.js", "Next.js static asset paths detected", "high"))
        if headers.get("x-powered-by", "").lower() == "next.js":
            findings.append(Finding("Next.js", "x-powered-by: Next.js header", "high"))

        # ── Vite ────────────────────────────────────────────────────────
        if re.search(r'type="module".*crossorigin', html):
            findings.append(Finding("Vite", "Vite-style module script detected", "medium"))
        if "/@vite" in html or "/node_modules/.vite" in html:
            findings.append(Finding("Vite", "Vite dev server references in source", "high"))

        # ── React ───────────────────────────────────────────────────────
        root_div = soup.find(id="root")
        if root_div and ("react" in html.lower() or "reactDOM" in html):
            findings.append(Finding("React", "React application detected (root div + React references)", "medium"))
        if "_reactListening" in html or "data-reactroot" in html:
            findings.append(Finding("React", "React DOM markers found", "medium"))

        # ── Nuxt / Vue ──────────────────────────────────────────────────
        if "__nuxt" in html or "nuxt" in headers.get("x-powered-by", "").lower():
            findings.append(Finding("Nuxt.js", "Nuxt.js application detected", "medium"))

        # ── Astro ───────────────────────────────────────────────────────
        if "astro" in html.lower() and ("astro-island" in html or "data-astro" in html):
            findings.append(Finding("Astro", "Astro framework detected", "medium"))

        # ── SvelteKit ───────────────────────────────────────────────────
        if "sveltekit" in html.lower() or "__sveltekit" in html:
            findings.append(Finding("SvelteKit", "SvelteKit framework detected", "medium"))

        if findings:
            result.score = min(100, len(findings) * 18)
        result.findings = findings
        return result

    def _check_content(self, soup, html) -> CategoryResult:
        result = CategoryResult("Content Signals", "📝")
        findings = []

        text = soup.get_text(separator=" ", strip=True).lower()

        # ── Generic marketing phrases ───────────────────────────────────
        phrase_hits = []
        for pattern in self.GENERIC_PHRASES:
            matches = re.findall(pattern, text, re.IGNORECASE)
            if matches:
                phrase_hits.append(pattern.replace(r"\b", "").replace("\\", ""))

        if len(phrase_hits) >= 5:
            findings.append(Finding(
                "Generic AI Copy",
                f"Found {len(phrase_hits)} generic marketing phrases typical of AI-generated copy",
                "high",
                ", ".join(phrase_hits[:5]),
            ))
        elif len(phrase_hits) >= 2:
            findings.append(Finding(
                "Generic Marketing Copy",
                f"Found {len(phrase_hits)} generic marketing phrases",
                "medium",
                ", ".join(phrase_hits[:3]),
            ))

        # ── Generic CTAs ────────────────────────────────────────────────
        cta_hits = []
        links_and_buttons = soup.find_all(["a", "button"])
        for el in links_and_buttons:
            el_text = el.get_text(strip=True).lower()
            for cta in self.GENERIC_CTAS:
                if cta in el_text:
                    cta_hits.append(cta)
                    break

        if len(cta_hits) >= 4:
            findings.append(Finding(
                "Generic CTAs",
                f"Found {len(cta_hits)} generic call-to-action buttons/links",
                "high",
                ", ".join(set(cta_hits)[:5]),
            ))
        elif len(cta_hits) >= 2:
            findings.append(Finding(
                "Generic CTAs",
                f"Found {len(cta_hits)} generic CTAs",
                "medium",
                ", ".join(set(cta_hits)),
            ))

        # ── Stock image CDNs ────────────────────────────────────────────
        stock_domains = ["unsplash.com", "images.pexels.com", "placeholder.com", "placehold.co",
                         "placekitten.com", "picsum.photos", "via.placeholder.com", "dummyimage.com"]
        stock_hits = []
        for img in soup.find_all("img"):
            src = img.get("src", "") or img.get("data-src", "")
            for domain in stock_domains:
                if domain in src:
                    stock_hits.append(domain)
                    break
        if stock_hits:
            findings.append(Finding(
                "Stock Images",
                f"Found {len(stock_hits)} images from stock/placeholder services",
                "medium",
                ", ".join(set(stock_hits)),
            ))

        # ── Placeholder / Lorem Ipsum ───────────────────────────────────
        if "lorem ipsum" in text:
            findings.append(Finding("Placeholder Text", "Lorem ipsum text detected", "high"))
        if re.search(r"your (company|brand|product) (name|here)", text, re.IGNORECASE):
            findings.append(Finding("Placeholder Text", "Placeholder company/brand text found", "high"))

        if findings:
            high_count = sum(1 for f in findings if f.confidence == "high")
            result.score = min(100, 15 + high_count * 22 + (len(findings) - high_count) * 10)
        result.findings = findings
        return result

    def _check_code_style(self, soup, html) -> CategoryResult:
        result = CategoryResult("Code Style Analysis", "🔬")
        findings = []

        # ── DOM nesting depth ───────────────────────────────────────────
        max_depth = self._max_nesting_depth(soup.body) if soup.body else 0
        if max_depth > 15:
            findings.append(Finding("Deep Nesting", f"Maximum DOM nesting depth: {max_depth} (excessive)", "high", f"{max_depth} levels"))
        elif max_depth > 10:
            findings.append(Finding("Deep Nesting", f"Maximum DOM nesting depth: {max_depth} (high)", "medium", f"{max_depth} levels"))

        # ── Tailwind utility class density ──────────────────────────────
        all_elements = soup.find_all(True)
        tailwind_heavy = 0
        for el in all_elements:
            classes = el.get("class", [])
            if isinstance(classes, list) and len(classes) > 8:
                tailwind_heavy += 1

        if tailwind_heavy > 20:
            findings.append(Finding(
                "High Utility Density",
                f"{tailwind_heavy} elements with 8+ utility classes — heavy Tailwind usage",
                "medium",
                f"{tailwind_heavy} elements",
            ))

        # ── TailwindCSS detection ───────────────────────────────────────
        tw_indicators = 0
        tw_classes = ["flex", "items-center", "justify-center", "rounded-lg", "px-4", "py-2", 
                      "bg-gradient-to-r", "text-sm", "font-medium", "space-y-", "gap-"]
        for cls in tw_classes:
            if f'"{cls}' in html or f" {cls}" in html or f'class="{cls}' in html:
                tw_indicators += 1
        if tw_indicators >= 6:
            findings.append(Finding("TailwindCSS", f"Strong TailwindCSS usage detected ({tw_indicators} indicator classes)", "medium"))
        elif tw_indicators >= 3:
            findings.append(Finding("TailwindCSS", "Possible TailwindCSS usage", "low"))

        # ── AI-style comments in source ─────────────────────────────────
        comment_pattern = re.compile(r"<!--\s*(This (component|section|div|element)|Main (content|section|layout)|The following)", re.IGNORECASE)
        ai_comments = comment_pattern.findall(html)
        if len(ai_comments) >= 3:
            findings.append(Finding(
                "AI-Style Comments",
                f"Found {len(ai_comments)} overly descriptive HTML comments typical of AI generation",
                "medium",
            ))

        # ── Inline event handlers (AI often uses these) ─────────────────
        inline_handlers = soup.find_all(attrs=lambda a: a and any(k.startswith("on") for k in a))
        if len(inline_handlers) > 5:
            findings.append(Finding(
                "Inline Handlers",
                f"{len(inline_handlers)} inline event handlers (onClick, etc.) — common in AI-generated code",
                "low",
            ))

        if findings:
            result.score = min(100, len(findings) * 18)
        result.findings = findings
        return result

    def _check_deployment(self, headers, parsed, url) -> CategoryResult:
        result = CategoryResult("Deployment Signals", "🚀")
        findings = []

        # ── Vercel ──────────────────────────────────────────────────────
        vercel_headers = [k for k in headers if k.lower().startswith("x-vercel")]
        if vercel_headers or ".vercel.app" in parsed.netloc:
            findings.append(Finding("Vercel", "Deployed on Vercel", "medium", ", ".join(vercel_headers[:3])))

        # ── Netlify ─────────────────────────────────────────────────────
        netlify_headers = [k for k in headers if k.lower().startswith("x-nf")]
        if netlify_headers or ".netlify.app" in parsed.netloc:
            findings.append(Finding("Netlify", "Deployed on Netlify", "medium"))

        # ── Cloudflare Pages ────────────────────────────────────────────
        if ".pages.dev" in parsed.netloc:
            findings.append(Finding("Cloudflare Pages", "Deployed on Cloudflare Pages", "low"))

        # ── Railway ─────────────────────────────────────────────────────
        if ".railway.app" in parsed.netloc:
            findings.append(Finding("Railway", "Deployed on Railway", "medium"))

        # ── Render ──────────────────────────────────────────────────────
        if ".onrender.com" in parsed.netloc:
            findings.append(Finding("Render", "Deployed on Render", "medium"))

        # ── Check for missing basics ────────────────────────────────────
        try:
            robots = requests.get(f"{parsed.scheme}://{parsed.netloc}/robots.txt", timeout=5)
            if robots.status_code == 404:
                findings.append(Finding("No robots.txt", "Missing robots.txt — common in quickly deployed vibe projects", "low"))
        except Exception:
            pass

        try:
            sitemap = requests.get(f"{parsed.scheme}://{parsed.netloc}/sitemap.xml", timeout=5)
            if sitemap.status_code == 404:
                findings.append(Finding("No sitemap", "Missing sitemap.xml", "low"))
        except Exception:
            pass

        if findings:
            high_count = sum(1 for f in findings if f.confidence == "high")
            result.score = min(100, 10 + high_count * 25 + (len(findings) - high_count) * 12)
        result.findings = findings
        return result

    def _check_design_patterns(self, soup, html) -> CategoryResult:
        result = CategoryResult("Design Pattern Analysis", "🎨")
        findings = []

        # ── Glassmorphism / Backdrop blur ───────────────────────────────
        style_content = html  # Check both inline and embedded styles
        if "backdrop-filter" in style_content or "backdrop-blur" in style_content:
            findings.append(Finding("Glassmorphism", "Backdrop blur / glassmorphism effects detected", "medium"))

        # ── Gradient backgrounds ────────────────────────────────────────
        gradient_count = len(re.findall(r"(bg-gradient-to-|linear-gradient|radial-gradient)", html))
        if gradient_count >= 5:
            findings.append(Finding("Heavy Gradients", f"Found {gradient_count} gradient references — AI loves gradients", "medium"))
        elif gradient_count >= 2:
            findings.append(Finding("Gradients", f"Found {gradient_count} gradient references", "low"))

        # ── Cookie-cutter section layout ────────────────────────────────
        sections = soup.find_all(["section", "div"], id=True)
        section_ids = [s.get("id", "").lower() for s in sections]
        section_classes = []
        for s in soup.find_all(["section", "div"], class_=True):
            section_classes.extend([c.lower() for c in (s.get("class") or [])])

        all_section_names = section_ids + section_classes
        template_hits = sum(1 for name in self.TEMPLATE_SECTION_NAMES if name in all_section_names)
        if template_hits >= 4:
            findings.append(Finding(
                "Template Layout",
                f"Found {template_hits}/7 cookie-cutter sections (hero, features, testimonials, ...)",
                "high",
            ))
        elif template_hits >= 2:
            findings.append(Finding(
                "Template Layout",
                f"Found {template_hits} template-style section names",
                "medium",
            ))

        # ── Card grid patterns ──────────────────────────────────────────
        card_elements = soup.find_all(class_=re.compile(r"card", re.IGNORECASE))
        if len(card_elements) >= 6:
            findings.append(Finding("Card Grid", f"Found {len(card_elements)} card components — typical AI layout pattern", "medium"))

        # ── Dark mode default ───────────────────────────────────────────
        html_tag = soup.find("html")
        if html_tag:
            html_class = " ".join(html_tag.get("class", []))
            if "dark" in html_class:
                findings.append(Finding("Dark Mode Default", "Page defaults to dark mode", "low"))

        body_tag = soup.find("body")
        if body_tag:
            body_style = body_tag.get("style", "")
            body_class = " ".join(body_tag.get("class", []))
            if any(dark in (body_style + body_class).lower() for dark in ["bg-gray-9", "bg-black", "bg-slate-9", "bg-zinc-9", "bg-neutral-9"]):
                findings.append(Finding("Dark Theme", "Dark background detected on body", "low"))

        # ── Neon / glow effects ─────────────────────────────────────────
        if re.search(r"(shadow-.*glow|neon|text-shadow.*#|box-shadow.*0\s+0\s+\d+px\s+\d+px)", html, re.IGNORECASE):
            findings.append(Finding("Glow Effects", "Neon/glow effects detected — popular in AI-generated designs", "low"))

        # ── Animated elements ───────────────────────────────────────────
        animations = re.findall(r"(animate-|@keyframes|transition-all|framer-motion|motion\.div)", html)
        if len(animations) >= 5:
            findings.append(Finding("Heavy Animations", f"Found {len(animations)} animation references", "low"))

        if findings:
            high_count = sum(1 for f in findings if f.confidence == "high")
            result.score = min(100, 10 + high_count * 25 + (len(findings) - high_count) * 10)
        result.findings = findings
        return result

    # ====================================================================
    # Helpers
    # ====================================================================

    def _max_nesting_depth(self, element, depth: int = 0) -> int:
        """Recursively find maximum DOM nesting depth."""
        if not hasattr(element, "children"):
            return depth
        max_d = depth
        for child in element.children:
            if hasattr(child, "name") and child.name:
                max_d = max(max_d, self._max_nesting_depth(child, depth + 1))
        return max_d

    @staticmethod
    def _get_verdict(score: int) -> tuple:
        if score >= 76:
            return "Almost Certainly Vibe Coded", "🔴"
        elif score >= 51:
            return "Probably Vibe Coded", "🟠"
        elif score >= 26:
            return "Mixed Signals", "🟡"
        else:
            return "Likely Human-Crafted", "🟢"
